<?php

/**
 * @file
 * Node Body validation install.
 */

/**
 * Converts node_body_validation_config config entity to node_body_validation.
 */
function node_body_validation_update_8001() {
  $old_config = \Drupal::configFactory()->getEditable('node_title_validation_config.node_title_validation_settings');
  $new_config = \Drupal::configFactory()->getEditable('node_title_validation.node_title_validation_settings');
  $new_config->set('node_body_validation_config', $old_config->get('node_body_validation_config'));
  $new_config->save();
  $old_config->delete();
}

/**
 * Implements hook_uninstall().
 */
function node_body_validation_uninstall() {
  // Deleting the validation settings while uninstalling the module.
  \Drupal::configFactory()->getEditable('node_body_validation.node_body_validation_settings')->delete();
}
